// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: api-gateway/pkg/query/pb/query.proto

package pb

import (
	pb "github.com/amiosamu/gophkeeper/api-gateway/pkg/services/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum Message type
type MessageType int32

const (
	MessageType_UNKNOWN_TYPE   MessageType = 0
	MessageType_LOGIN_PASSWORD MessageType = 1
	MessageType_TEXT           MessageType = 2
	MessageType_BINNARY        MessageType = 3
	MessageType_CARD           MessageType = 4
	MessageType_ANY            MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "LOGIN_PASSWORD",
		2: "TEXT",
		3: "BINNARY",
		4: "CARD",
		5: "ANY",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN_TYPE":   0,
		"LOGIN_PASSWORD": 1,
		"TEXT":           2,
		"BINNARY":        3,
		"CARD":           4,
		"ANY":            5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gateway_pkg_query_pb_query_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_api_gateway_pkg_query_pb_query_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_api_gateway_pkg_query_pb_query_proto_rawDescGZIP(), []int{0}
}

// Query
type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=query.MessageType" json:"type,omitempty"`
	UserID int64       `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_pkg_query_pb_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_pkg_query_pb_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_pkg_query_pb_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN_TYPE
}

func (x *QueryRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

var File_api_gateway_pkg_query_pb_query_proto protoreflect.FileDescriptor

var file_api_gateway_pkg_query_pb_query_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x70, 0x62, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x2a, 0x61,
	0x70, 0x69, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0c, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x2a, 0x5d, 0x0a, 0x0b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x4f,
	0x47, 0x49, 0x4e, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x49, 0x4e, 0x4e,
	0x41, 0x52, 0x59, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x41, 0x52, 0x44, 0x10, 0x04, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x4e, 0x59, 0x10, 0x05, 0x32, 0x4c, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x13, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x78, 0x6b, 0x6f, 0x70, 0x63, 0x61, 0x6b, 0x2f,
	0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_gateway_pkg_query_pb_query_proto_rawDescOnce sync.Once
	file_api_gateway_pkg_query_pb_query_proto_rawDescData = file_api_gateway_pkg_query_pb_query_proto_rawDesc
)

func file_api_gateway_pkg_query_pb_query_proto_rawDescGZIP() []byte {
	file_api_gateway_pkg_query_pb_query_proto_rawDescOnce.Do(func() {
		file_api_gateway_pkg_query_pb_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_gateway_pkg_query_pb_query_proto_rawDescData)
	})
	return file_api_gateway_pkg_query_pb_query_proto_rawDescData
}

var file_api_gateway_pkg_query_pb_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gateway_pkg_query_pb_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_gateway_pkg_query_pb_query_proto_goTypes = []interface{}{
	(MessageType)(0),              // 0: query.MessageType
	(*QueryRequest)(nil),          // 1: query.QueryRequest
	(*pb.QueryResponseArray)(nil), // 2: services.QueryResponseArray
}
var file_api_gateway_pkg_query_pb_query_proto_depIdxs = []int32{
	0, // 0: query.QueryRequest.type:type_name -> query.MessageType
	1, // 1: query.QueryService.Query:input_type -> query.QueryRequest
	2, // 2: query.QueryService.Query:output_type -> services.QueryResponseArray
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gateway_pkg_query_pb_query_proto_init() }
func file_api_gateway_pkg_query_pb_query_proto_init() {
	if File_api_gateway_pkg_query_pb_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_gateway_pkg_query_pb_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_gateway_pkg_query_pb_query_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_pkg_query_pb_query_proto_goTypes,
		DependencyIndexes: file_api_gateway_pkg_query_pb_query_proto_depIdxs,
		EnumInfos:         file_api_gateway_pkg_query_pb_query_proto_enumTypes,
		MessageInfos:      file_api_gateway_pkg_query_pb_query_proto_msgTypes,
	}.Build()
	File_api_gateway_pkg_query_pb_query_proto = out.File
	file_api_gateway_pkg_query_pb_query_proto_rawDesc = nil
	file_api_gateway_pkg_query_pb_query_proto_goTypes = nil
	file_api_gateway_pkg_query_pb_query_proto_depIdxs = nil
}
